---
AllCops:
  TargetRubyVersion: 2.4

# Style
Style/TrailingCommaInArguments:
  Description: We're not living in JSON world anymore.
  EnforcedStyleForMultiline: consistent_comma

# Metrics
Metrics/LineLength:
  Description: People have wide screens, use them.
  Max: 140
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 20
